[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = false
solc = "0.8.24"
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@uniswap/v3-periphery/=lib/v3-periphery/",
  "@uniswap/v3-core/=lib/v3-core/"
]

[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/IvMTCy2p4_jk6PCd5-2Gu"

